[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "epiquote"
version = "0.0.0"
description = "A quote database website"
authors = [
    { name = "Antoine Pietri", email = "antoine.pietri1@gmail.com" }
]
license = { text = "GPL-3.0-or-later" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.3,<7.0.0",
    "django-crispy-forms>=2.0",
    "crispy-bootstrap5>=2.0",
    "django-contrib-comments>=2.2.0,<3.0.0",
    "psycopg2-binary>=2.9.6,<3.0.0",
    "django-registration>=5.2.1,<6.0.0",
    "dj-database-url>=3.1.2,<4.0.0",
    # Waiting for Django 4 compat:
    # https://gitlab.cri.epita.fr/cri/packages/social-auth-backend-epita/-/merge_requests/5
    # "social-auth-backend-epita>=1.0.2,<2.0.0",
]

[project.optional-dependencies]
prod = [
    "gunicorn>=23.0.0,<24.0.0",
    "ipython>=9.6.0,<10.0.0",
]

[project.urls]
Repository = "https://github.com/seirl/epiquote"

[tool.hatch.build.targets.wheel]
packages = ["epiquote", "quotes"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.black]
line-length = 79
skip-string-normalization = true
extend-exclude = '''
/(
  | migrations
)/
'''
