# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quotevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='quotes',
            field=models.ManyToManyField(related_name='users_favorite', to='quotes.Quote'),
        ),
    ]
