# Generated by Django 2.0.3 on 2018-03-29 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0004_favorites_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotevote',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='voters',
            field=models.ManyToManyField(related_name='voted_quotes', through='quotes.QuoteVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotevote',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quotes.Quote'),
        ),
        migrations.AlterField(
            model_name='quotevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
