# Generated by Django 2.0.3 on 2018-03-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quote_fans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
